on:
  release:
    types: [published]

name: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']
        cfg:
          - {os: windows-2025, architecture: x64}
          - {os: windows-11-arm, architecture: arm64}
          - {os: macos-26-intel, architecture: x64}
          - {os: macos-26, architecture: arm64}
          - {os: ubuntu-26.04, architecture: x64}
          - {os: ubuntu-26.04-arm, architecture: arm64}

    runs-on: ${{ matrix.cfg.os }}

    steps:
    - name: Clone
      uses: actions/checkout@v7

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.cfg.architecture }}

    - name: Install dependencies
      run: |
        pip install build twine

    - name: Build
      run: |
        python -m build .

    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
      run: |
        twine upload dist/* --skip-existing --repository testpypi
