on:
  release:
    types: [published]

name: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: windows-2025, python-version: '3.11', architecture: x64 }
          - { os: windows-2025, python-version: '3.12', architecture: x64 }
          - { os: windows-2025, python-version: '3.13', architecture: x64 }
          - { os: windows-2025, python-version: '3.14', architecture: x64 }
          - { os: windows-11-arm, python-version: '3.11', architecture: arm64 }
          - { os: windows-11-arm, python-version: '3.12', architecture: arm64 }
          - { os: windows-11-arm, python-version: '3.13', architecture: arm64 }
          - { os: windows-11-arm, python-version: '3.14', architecture: arm64 }
          - { os: macos-15, python-version: '3.11', architecture: arm64 }
          - { os: macos-15, python-version: '3.12', architecture: arm64 }
          - { os: macos-15, python-version: '3.13', architecture: arm64 }
          - { os: macos-15, python-version: '3.14', architecture: arm64 }

    runs-on: ${{ matrix.cfg.os }}

    steps:
    - name: Clone
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.cfg.python-version }}
        architecture: ${{ matrix.cfg.architecture }}

    - name: Install dependencies
      run: |
        pip install build twine

    - name: Build
      run: |
        python -m build .

    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.AMULET_MUTF8_PYPI_PASSWORD }}
      run: |
        twine upload dist/* --skip-existing
