on:
  release:
    types: [published]

name: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26, ubuntu-26.04, ubuntu-26.04-arm, windows-2025, windows-11-arm]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Clone
      uses: actions/checkout@v7.0.0
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v6.3.0
      with:
        python-version: 3.x

    - name: Install twine
      run: |
        pip install twine

    - name: Set up cibuildwheel and build wheels
      uses: pypa/cibuildwheel@v4.1.0

    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
      run: |
        twine upload wheelhouse/* --skip-existing --repository testpypi
